#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Nov 16 16:55:23 MSK 2025
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.6.1.zip
